# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e6cdb45374a5e3eb5e786565e369b06d7248bdd78e51a868020eba90098324f807abe59400f31a3b01ad7af23d1cb42b1da96b5aeb38bf9c5ef800761a21dcc

test:
  secret_key_base: 3a661adf7a01e3770c790baecd8a211ea6bb176a21fde5a7e8d65ee63e569740ed194c7c59295c7121c05da4c2f117cd0d28800713be0abf8c5fb4e0f8bfac86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
